#!/bin/sh

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
xwallpaper --zoom ~/Pictures/wallpapers/current.jpg &			# set the background
xrdb ~/.config/x11/xresources	# Uncomment to use Xresources colors/settings on startup

autostart="mpd mpdas picom dunst pipewire pipewire-pulse wireplumber unclutter remapd dwmblocks sxhkd"


for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

#[ -n "$xrdbpid" ] && wait "$xrdbpid"
