#!/bin/sh

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
~/.fehbg &			# set the background with the `setbg` script
xrdb ~/.Xresources	# Uncomment to use Xresources colors/settings on startup

autostart="mpd picom dunst unclutter pipewire remapd xbindkeys"


for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

#[ -n "$xrdbpid" ] && wait "$xrdbpid"
